name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Run lint
        run: ./gradlew lintDebug


  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run test
        run: ./gradlew test


#  test:
  #    runs-on: macos-latest
  #    steps:
  #      - name: checkout
  #        uses: actions/checkout@v3
  #
  #      - name: run tests
  #        uses: reactivecircus/android-emulator-runner@v2
  #        with:
  #          api-level: 29
  #          script: ./gradlew connectedCheck
  instrumentation-test:
    needs: [unit-test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create directory for jni libs
        run: mkdir app/libs && mkdir app/libs/arm64-v8a

      - name: Create Android emulator
        run: |
            sdkmanager --install "system-images;android-31;google_apis;x64"
            echo "no" | avdmanager --verbose create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-31;google_apis;x86_64'

      - name: Copy jar files to app folder
        run: gradle extractLibs

      - name: Launch Emulator
        run: |
            $ANDROID_SDK_ROOT/emulator/emulator -avd testAVD

      - name: Run espresso test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
#          target: default
#          arch: x64
#          profile: pixel_xl
          script: ./gradlew connectedCheck

#      - name: Run a one-line script
#        run: echo Hello world
#
#      - name: Run a multi-line script
#        run: |
#              echo Run other lines
#              echo test, deploy and built
#
