name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Run lint
        run: ./gradlew lintDebug


  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run test
        run: ./gradlew test

      - name: Clean Gradle cache
        run: ./gradlew cleanBuildCache --debug

  instrumentation-test:
    #needs: [unit-test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clean Gradle cache
        run: ./gradlew cleanBuildCache --debug

      - name: Run espresso test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: Nexus 5X
          serial-port: 5554
          script: ./gradlew connectedDebugAndroidTest --info --stacktrace
      - name: Wait for emulator to start up
        run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

      - name: Run instrumentation tests
        run: ./gradlew connectedDebugAndroidTest --no-daemon

##      - name: Run a one-line script
##        run: echo Hello world
##
##      - name: Run a multi-line script
##        run: |
##              echo Run other lines
##              echo test, deploy and built
##
