name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Run lint
        run: ./gradlew lintDebug
      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: index.html
          path: app/build/reports/line-results-debug.html
#      - name: Run a one-line script
#        run: echo Hello world
#
#      - name: Run a multi-line script
#        run: |
#              echo Run other lines
#              echo test, deploy and built
#
